[package]
name = "typodist"
version = "0.1.0"
authors = ["Matthias Schmitt <male.schmitt@posteo.de>"]
edition = "2018"

[dependencies]
lazy_static = "1.3"
clap = "2.33"
structopt = "0.2"

[lib]
name = "typodist_lib"
path = "src/lib.rs"


[[bin]]
name = "typodist"
path = "src/main.rs"
